### ISSUE TITLE
Nvidia Components can't access API Keys 

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-core-integrations#745] opened 2024-05-22 16:09 UTC
**Describe the bug**
@shadeMe and @silvanocerza - here's the reason for our dirty fix for nvidia integration today, as well as steps to reproduce.

Prior info:
- I did _not_ have this bug locally, however, the minute I setup a dockerized environment and deployed the pipeline with hayhooks I did.
- This issue is across all NVIDIA components
- I was using the hosted models for which you can get API keys [here](https://build.nvidia.com/)
- All the code you need is public, including docker compose files etc in our [nvidia-haystack repo](https://github.com/deepset-ai/nvidia-haystack)
- I provided a dirty fix and we released nvidia-haystack 0.0.3 to ublock our work with them. The PR that was merged is #744 

The issue is that although `NVIDIA_API_KEY` env var _is_ available, and although we've confirmed it works locally, when we deploy `rag.yaml` (you can simplify it by replacing retrieval with link content fetching), we will get a 401 unauthorized error seemingly coming from the nim backend components.

**To Reproduce**
Cone the repo and:
- `docker-compose up`
- pip install nvidia-haystack==0.0.2 (old version which caused the issue)
- (If you're gonna use the same rag with Qdrant, also pip install qdrant-haystack)
- (If your're gonna use the same rag with Qdrant: python indexing.py)
- hayhooks deploy rag.yaml
- Try runninng a query..

**Comment by TuanaCelik** [comment] 2024-06-14 12:11
Update and more context if anyone needs it. 
I created a quick fix to the Nvidia NIM components to unblock the work with Nvidia and out co-authored article. 

The issue that I lay out above about the api keys still stand, and you should still be able to reproduce it with hayhooks/docker using the same repository.

The point is, that this was a simple fix that I noticed and Massi agreed that the issue stemmed from the fact that there were no default api key environment variables provided in some components. But this might not be the right fix. If you decide that the fix was ok, then this issue can be closed, if not, someone should reproduce the steps above to see why things go wrong and provide an alternative fix.

**Comment by silvanocerza** [comment] 2024-06-24 10:02
Just tested, can't reproduce. 
Closing.

**Closed by silvanocerza** 2024-06-24 10:02 UTC
Labels: bug, P1, integration:nvidia
