### ISSUE TITLE
Fix connection with Weaviate Cloud Service 

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#697] opened 2024-04-29 08:00 UTC
The `WeaviateDocumentStore` can't properly connect with the Weaviate Cloud Service as of now.

We need to fix this, there's already #624 that attempted a quick fix but we should test and implement it properly.

**Comment by masci** [comment] 2024-05-06 07:32
Duplicate of https://github.com/deepset-ai/haystack-core-integrations/issues/662

**Closed by masci** 2024-05-06 07:32 UTC
Labels: bug, P2, integration:weaviate
