### ISSUE TITLE
AmazonBedrockChatGenerator is not working with the Mixtral model

### ISSUE THREAD

**Issue by vish9812** [deepset-ai/haystack-core-integrations#743] opened 2024-05-21 07:07 UTC
**Describe the bug**
Calling `run` with the Mixtral model - `mistral.mixtral-8x7b-instruct-v0:1` is failing with the following error message: `Could not inference Amazon Bedrock model mistral.mixtral-8x7b-instruct-v0:1 due: An error occurred (ValidationException) when calling the InvokeModel operation: Validation Error`.

While the code runs successfully with the Mistral model - `mistral.mistral-7b-instruct-v0:2`.

**To Reproduce**
```python
AmazonBedrockChatGenerator(
            # model="mistral.mistral-7b-instruct-v0:2", It passes
            # model="mistral.mixtral-8x7b-instruct-v0:1", It fails
).run(prompt)
```

**Describe your environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Haystack version: 2.1.2
 - Integration version: 0.7.1

PS: I've access to both the models, so, it's not an access issue.

**Comment by anakin87** [comment] 2024-05-21 08:13
duplicate of #732

**Comment by vish9812** [comment] 2024-05-21 09:24
Actually, this is a different issue. I'm able to run inference for the Mi**s**tral Model via HF access token.
But the issue here is that while the Mistral model works fine. The Mi**x**tral model gives the above mentioned validation error.

**Comment by sjrl** [comment] 2024-06-05 05:08
The issue I believe is linked to this code block: https://github.com/deepset-ai/haystack-core-integrations/blob/6aaf523636d923ce158c46ea39a057f5529b5a17/integrations/amazon_bedrock/src/haystack_integrations/components/generators/amazon_bedrock/generator.py#L56C1-L63C6

```python
    SUPPORTED_MODEL_PATTERNS: ClassVar[Dict[str, Type[BedrockModelAdapter]]] = {
        r"amazon.titan-text.*": AmazonTitanAdapter,
        r"ai21.j2.*": AI21LabsJurassic2Adapter,
        r"cohere.command.*": CohereCommandAdapter,
        r"anthropic.claude.*": AnthropicClaudeAdapter,
        r"meta.llama2.*": MetaLlama2ChatAdapter,
        r"mistral.*": MistralAdapter,
    }
```

It looks in Haystack v1 we replaced the last line with 
```python
r"mistral.mi[sx]tral.*": MistralAIAdapter,
```

so I think an update to this regex expression should do the trick

**Comment by Amnah199** [comment] 2024-06-25 09:09
We tested this on different machines and were not able to produce the bug. @vish9812 are you still facing this issue?

**Comment by Amnah199** [comment] 2024-06-26 13:41
Closing this issue as the bug was not detected.

**Closed by Amnah199** 2024-06-26 13:41 UTC
Labels: bug, P1
