### ISSUE TITLE
Rename the `QdrantRetriever`  + `/retrievers` folder

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#134] opened 2023-12-20 16:35 UTC
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to have predictable names for components and other retriever names contain the retrieval method

**Describe the solution you'd like**
Renaming the `QdrantRetriever` as `QdrantEmbeddingRetriever` to align with the current convention. Also, since we foresee `QdrantSparseRetriever` and `QdrantHybridRetriever`, it makes sense to create a new `retrievers` folder and move `QdrantEmbeddingRetriever` into it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sahusiddharth** [comment] 2023-12-27 03:24
@bilgeyucel 

Can you please confirm?

Things to do:-

- [ ] Rename the current [QdrantRetriever](https://github.com/deepset-ai/haystack-core integrations/blob/main/integrations/qdrant/src/qdrant_haystack/retriever.py#L9) to `QdrantEmbeddingRetriever`.
- [ ] Create a new folder named `retriever` inside src/qdrant_haystack and put retriever.py inside it.

**Comment by sahusiddharth** [comment] 2024-01-29 19:10
Hi @silvanocerza , I hope you're doing well. I noticed that the issue is still open. Could you please provide an update on its status?

**Comment by silvanocerza** [comment] 2024-02-01 09:23
@sahusiddharth this can be closed I think, I left it open cause it was also about adding a new `retrievers` folder but we've done that with #255.

I'll close it as done. Thanks for pinging. 🙏

**Closed by silvanocerza** 2024-02-01 09:23 UTC
Labels: feature request, integration:qdrant
