### ISSUE TITLE
Issue of ollama supporting the function call feature

### ISSUE THREAD

**Issue by fan-chao** [deepset-ai/haystack-core-integrations#913] opened 2024-07-19 09:42 UTC
**Describe the bug**
Hello, thank you for providing haystack such a useful LLM framework.

I found that ollama can now support the function call feature https://github.com/ollama/ollama/commit/d02bbebb11c2e9c391ee3af30ba3437e67d1b7a8.
Then I tested using the OllamaChatGenerator interface of haystack, the test code is as follows:

```python
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "获取指定城市的天气信息",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "城市名称，如：北京",
                    }
                },
                "required": ["location"],
            },
        }
    }
]

chat_generator = OllamaChatGenerator(model="mistral",
                            url = "http://192.168.1.101:11434/api/chat",
                            generation_kwargs={
                              "num_predict": 4096,
                              "temperature": 0.0,
                              },
                            )

messages5 = [
    ChatMessage.from_user("what is whether of beijing today?"),
]
response = chat_generator.run(messages=messages5, generation_kwargs={"tools": tools})
print(response)
```

When using the OllamaChatGenerator to call the ollama interface, the return result is as follows, that is, there is no function call feature result.

```python
{'replies': [ChatMessage(content=" To provide you with the current weather in Beijing, I would typically use a service like OpenWeatherMap API. However, as a text-based AI model, I don't have real-time capabilities to access external data sources directly. You can check the current weather in Beijing by visiting a reliable weather website or using a mobile app that provides this information.\n\nFor your convenience, here is a link to the Beijing weather forecast on Weather.com: https://weather.com/weather/today/lx-CNXX0126:1:US", role=<ChatRole.ASSISTANT: 'assistant'>, name=None, meta={'model': 'mistral', 'created_at': '2024-07-19T09:00:40.619199632Z', 'done_reason': 'stop', 'done': True, 'total_duration': 1311717475, 'load_duration': 14763572, 'prompt_eval_count': 13, 'prompt_eval_duration': 26318000, 'eval_count': 121, 'eval_duration': 1226776000})]}
```

Then I used the OpenAIChatGenerator interface to call ollama:

```python
chat_generator2 = OpenAIChatGenerator(model="mistral", api_base_url='http://192.168.1.101:11434/v1/')
```

The output result is as follows:

```python
{'replies': [ChatMessage(content='[{"id": "call_lb0y3k1z", "function": {"arguments": "{\\"location\\":\\"Beijing\\"}", "name": "get_current_weather"}, "type": "function"}]', role=<ChatRole.ASSISTANT: 'assistant'>, name=None, meta={'model': 'mistral', 'index': 0, 'finish_reason': 'stop', 'usage': {'completion_tokens': 22, 'prompt_tokens': 85, 'total_tokens': 107}})]}
```

You can see that the function call feature has been implemented.
So the current interface OllamaChatGenerator seems to have no function call feature. So when will this issue be fixed?

**To Reproduce**
Steps to reproduce the behavior. Feel free to link a Colab we can run to investigate the issue.

**Describe your environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Haystack version: 2.3.0
 - Integration version: 2.16.3
 - Ollama: 0.2.7

**Comment by lbux** [comment] 2024-07-25 02:14
Also, it seems like Tools supported isn't fully ironed out for Ollama as seen here https://github.com/ollama/ollama/issues/5796. Once the issue is closed (if the PR gets merged), you should try running your example again after rebuilding Ollama from source to see if the issue persists.

There is more work being done for ChatMessage, so once that is ironed out, proper Tools support can be added.

**Comment by vblagoje** [comment] 2024-08-15 10:57
Thanks for these comments @lbux and @fan-chao We'll close this one in favor of https://github.com/deepset-ai/haystack/issues/8190

**Closed by vblagoje** 2024-08-15 10:57 UTC
Labels: bug, integration:ollama
